#!/bin/sh

# allow two-finger and edge scrolling vertically and horizontally:
#xinput set-prop "SynPS/2 Synaptics TouchPad" "Synaptics Edge Scrolling" 1 1 0
#xinput set-prop "SynPS/2 Synaptics TouchPad" "Synaptics Two-Finger Scrolling" 1 1
#xinput set-prop "SynPS/2 Synaptics TouchPad" "Synaptics Scrolling Distance" 86 120
# disable tapping completely:
#xinput set-prop "SynPS/2 Synaptics TouchPad" "Synaptics Tap Action" 0 0 0 0 0 0 0
#xinput set-prop "SynPS/2 Synaptics TouchPad" "Synaptics Click Action" 0 0 0

# set keyboard map (effect on login is to allow switching):
#model is logitech_g15 or thinkpad60
# updates seem to be missed without piping to xkbcomp
setxkbmap -layout cyborg16,cyborg16\
    -variant colemak4_ch,basic\
    -option grp:sclk_toggle,grp_led:caps,compose:menu,compose:prsc\
    -model thinkpad60\
#    -print | xkbcomp - $DISPLAY
#,lv3:rwin_switch,lv3:ralt_switch

# enable key repeat on capslock (still needs to be done repeatedly?)
xset r 66
#while true; do xset r 66; sleep 5; done &

if [ -f ~/.Xmodmap ]
then
	xmodmap ~/.Xmodmap
fi
if [ -f ~/.xbindkeysrc ]
then
        killall xbindkeys
	xbindkeys
fi

#Logitech G9 horiz scrolling:
# Note: Can't use string ID because we have two identical strings. Do a bit of
# jiggery-pokery instead to get a numerical ID.
G9ID="$(xinput --list --long | egrep "Buttons supported: 24" -B3 | egrep "Logitech G9" | cut -f2 | cut -d= -f2)"
if [ -n "$G9ID" ]
then
	# found the G9 with the correct number of buttons; do mapping:
	xinput set-button-map "$G9ID" 1 2 3 4 5 11 12 8 9 10 6 7
fi

