#!/bin/sh
# rm with different semantics

#real rm:
RM=/bin/rm
HELP=""
FORCE=""

while test $# -ne 0; do
    arg=$1
    shift
    
    # Match options
    case $arg in
        (-f)
            FORCE="t"
            continue;;
        (-h)
            HELP="t"
            break;;
        (-*)
            echo "Illegal argument: $arg"
            HELP="t"
            break;;
    esac
    
    # Match paths (should really happen after all options have been matched,
    # but I can't work out how to do that properly in sh)
    if [ -L "$arg" ]; then
        # is a link, just delete
        $RM -f "$arg"
    elif [ -d "$arg" ]; then
        if [ -n "$FORCE" ]; then
            $RM -rf "$arg"
        else
            rmdir --ignore-fail-on-non-empty "$arg"
            if [ -d "$arg" ]; then
                read -p "rm: recursively remove directory \`$arg\`? " q
                if [ "$q" = "y" ]; then
                    $RM -rf "$arg"
                fi
            fi
        fi
    elif [ -e "$arg" ]; then
        if [ -n "$FORCE" ]; then
            $RM -f "$arg"
        else
            $RM -i "$arg"
        fi
    else
        echo "rm: \`$arg\` is not a file, link or directory"
    fi
done

if [ -n "$HELP" ]; then
    echo "Usage: $0 [OPTIONS] PATHS"
    echo "Deletes each PATH listed in a more sensible way than standard rm."
    echo ""
    echo "Options (must preceed paths to have an effect):"
    echo "    -h\tPrint this message."
    echo "    -f\tDelete without confirmation."
    exit 1
fi
