#!/usr/bin/env python

import sys
import os
from optparse import OptionParser

begin = '/home/photos/'
backgrounds=os.path.join(os.environ['HOME'],'pictures/backgrounds/photos/')

parser = OptionParser("Usage: %prog [options] FILES")
parser.add_option("-f",action="store_true",dest="force_removal",default=False,help="remove existing links/files at target")
(options,others)=parser.parse_args(args=sys.argv[1:])

for w in others:
    w=os.path.abspath(w)
    dest=os.path.join(backgrounds,os.path.relpath(w,start=begin).replace('/','-'))
    if os.path.exists(dest) and (os.path.isfile(dest) or os.path.islink(dest)):
        if options.force_removal:
            os.remove(dest)
        else:
            print >>sys.stderr,"Error:",dest,"already exists (use -f to automatically remove)"
            continue
    os.symlink(w,dest)
