#!/bin/sh

# Other tweaks:
# Add to boot command line: nmi_watchdog=0 pcie_aspm=force


# Upek Biometric Touchchip/Touchstrip Fingerprint Sensor:
echo auto | sudo tee /sys/bus/usb/devices/1-1.3/power/level
# Broadcom Corp. Bluetooth Controller:
echo auto | sudo tee /sys/bus/usb/devices/1-1.4/power/level

#Not sure whether the rest is relevent:
exit 0


#TODO: make sure user is root!

# ALPM
cd /sys/class/scsi_host
for d in host*;
do
    # may not exist for all adapters!
    if [ -f $d/link_power_management_policy ];
    then
        # could also use medium_power; defaults to max_performance
        echo min_power > $d/link_power_management_policy
    fi
done

# Bluetooth (3W according to powertop):
/etc/rc.d/bluetooth stop
rmmod btusb

# Audio... what to do?
