#!/bin/sh
DIR=`dirname $0`
if [ "$#" -eq "2" -a "$1" = "save" ]
then
	FILE="$DIR/plasma-appletsrc-$2"
	cp .kde/share/config/plasma-appletsrc $FILE
elif [ "$#" -eq "2" -a "$1" = "load" ]
then
	if [ "$2" = "clean" ]
	then
		kquitapp plasma
		rm -f .kde/share/config/plasma-appletsrc
	else
		FILE="$DIR/plasma-appletsrc-$2"
		if [ ! -f $FILE ]
		then
			echo "No such file: $FILE"
			exit 1
		fi
		kquitapp plasma
		cp $FILE .kde/share/config/plasma-appletsrc
	fi
	plasma
else
	echo "Usage: $0 op name"
	echo "where op is:"
	echo "\tsave\tSave current plasma-appletsrc under name"
	echo "\tload\tLoad current plasma-appletsrc from name (or default config if name = clean)"
	exit 1
fi
