#!/bin/sh

# disabling HDMI output with pavucontrol then restarting the sound server with
# 'sudo alsa force-reload' was necessary to work around some bug

# Show devices:
# pactl list | grep -A4 "Source #"

# icecast config is in /etc/icecast2/icecast.xml
# admin page URL: http://localhost:8000/admin/stats.xml

gst-launch \
        pulsesrc device=alsa_output.pci-0000_00_1b.0.analog-stereo.monitor ! \
        audioconvert ! vorbisenc ! oggmux ! \
        shout2send mount=/stream.ogg port=8000 password=wings50 ip=127.0.0.1
