#!/bin/bash

umask 0133
#check arguments
if [ $# -lt 2 ];
then
	echo "Usage: wav2mp3 <indir> <outdir> <prefix>";
	echo "If <outdir> does not exist it will be created.";
	echo "If <prefix> is used, it will be prefixed to output filenames."
	exit 1;
fi;
if [ ! -d $1 ];
then
	echo "Usage: wav2mp3 <indir> <outdir>";
	echo "If <outdir> does not exist it will be created.";
	echo "If <prefix> is used, it will be prefixed to output filenames."
	exit 1;
fi;
if [ -d $2 ]; then
	if [ ! -w $2 ];
	then
		echo "Error: write permission not granted in $2";
		exit 1;
	fi;
elif [ -e $2 ]; then
	echo "Usage: wav2mp3 <indir> <outdir>";
	echo "If <outdir> does not exist it will be created.";
	echo "If <prefix> is used, it will be prefixed to output filenames."
	exit 1;
else
	mkdir $2;
fi;

WAVs=$1/*.wav;

for WAV in $WAVs ; do
	if [ $3 = "" ] ; then
		MP3=$2/$(basename $WAV .wav).mp3 ;
	else
		MP3=$2/$3-$(basename $WAV .wav).mp3 ;
	fi;
	lame --vbr-new $WAV $MP3 ;
done;
