#!/usr/bin/env python
import sys
import os
import tempfile

# Configure your favorite diff program here.
DIFF3 = "/usr/bin/kdiff3"

# Subversion provides the paths we need as the last three parameters.
MINE  = sys.argv[-3]
OLDER = sys.argv[-2]
YOURS = sys.argv[-1]

# Create a temporary file for output
tfile = tempfile.NamedTemporaryFile(delete=False)
tname = tfile.name
tfile.close()

# Call the merge command (change the following line to make sense for
# your merge program).
cmd = [DIFF3, OLDER, MINE, YOURS, '-o', tname]
os.execv(cmd[0], cmd)

# After performing the merge, this script needs to print the contents
# of the merged file to stdout.  Do that in whatever way you see fit.
# Return an errorcode of 0 on successful merge, 1 if unresolved conflicts
# remain in the result.  Any other errorcode will be treated as fatal.

tf = open(tname)
while True:
    content=tf.read(4096)
    if(len(content)==0):
        break
    print content,

os.remove(tname)
